default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: filmpost_app_development
test:
  <<: *default
  database: filmpost_app_test
production:
  <<: *default
  database: filmpost_app_production
  username: filmpost_app
  password: <%= ENV['FILMPOST_APP_DATABASE_PASSWORD'] %>
